### ISSUE TITLE
kdbench.scra - No such file or directory

### ISSUE THREAD

**Issue by MurzNN** [sysnet4admin/kDbench#1]
When I'm trying to launch kdbench with storage class name - I've got the error:
```
~/temp/2022-09/kDbench$ ./kdbench ceph-block
cp: cannot stat '/srv/korepov/.kdbench/kdbench.scra': No such file or directory
```
Without arguments it starts well and shows me the list of storage classes:
```
~/temp/2022-09/kDbench$ ./kdbench 
ceph-block
ceph-bucket
ceph-filesystem
```

Where can be the problem and how to fix it?

**Comment by MurzNN** [comment]
Seems that path for this file is hard-coded:
https://github.com/sysnet4admin/kDbench/blob/b1b23f3309c8f5f729b755ae8719984c355cb5b8/kdbench#L24
Maybe make it relative to the script directory?

**Comment by sysnet4admin** [comment]
@MurzNN Yes it is hard coded. so it cannot move to other directory from `~/.kdbench` files

**Comment by MurzNN** [comment]
So, maybe make it relative, to not force the directory structure? Now, because of this, it works only when git is cloned to the `~/.kdbench` - it's a bit strange.

**Comment by sysnet4admin** [comment]
Yes all of them are fixed structure. if you want to modify, fork and modify it.
